// This file is part of Athanor, the Azodoc document engine.
// Copyright (C) 2026 The Athanor Studio Developers
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published
// by the Free Software Foundation, version 3 of the License only.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program. If not, see <https://www.gnu.org/licenses/>.

//! 从 [`mapping`] 映射表生成 ProseMirror Schema 工件。
//!
//! 产物（黄金文件入库，`tests/golden.rs` 逐字节比对）：
//! - `gen/aludel-schema.json`：PM `Schema.fromJSON` 兼容的纯数据 spec；
//! - `gen/schema.mjs`：ES module 包装，供 Aludel 前端 `import { schemaSpec }`。
//!
//! 重新生成：`cargo run -p azodoc-pm --bin generate`。

use serde_json::{json, Map, Value};

use crate::mapping::{pm_attr_name, table_role, AttrDef, MARKS, NODES};

fn attrs_json(attrs: &[AttrDef]) -> Value {
    let mut out = Map::new();
    for a in attrs {
        let default = match a.spec {
            crate::mapping::AttrSpec::Text(s) => json!(s),
            crate::mapping::AttrSpec::Int(i) => json!(i),
            // 跨度 attr 的 PM 默认是 1——TableMap 拿 attrs.colspan/rowspan
            // 直接做算术，null 会让整表 zero_sized。
            crate::mapping::AttrSpec::Span => json!(1),
            crate::mapping::AttrSpec::OptText
            | crate::mapping::AttrSpec::OptInt
            | crate::mapping::AttrSpec::OptBool
            | crate::mapping::AttrSpec::OptJson => Value::Null,
        };
        out.insert(
            pm_attr_name(a.name).to_string(),
            json!({ "default": default }),
        );
    }
    Value::Object(out)
}

/// PM `Schema.fromJSON` 兼容的 schema spec（含 `$azodoc` 溯源元数据，PM 会忽略未知键）。
pub fn schema_spec() -> Value {
    let mut nodes = Map::new();
    for d in NODES {
        let mut spec = Map::new();
        if !d.group.is_empty() {
            spec.insert("group".into(), json!(d.group));
        }
        // PM 依据 `inline: true` 判定行内节点：缺失时 "inline*" 内容表达式会拒绝
        // 这些节点（"Mixing inline and block content"）。text 由 PM 特判，无需此标志。
        if d.group == "inline" && d.pm_name != "text" {
            spec.insert("inline".into(), json!(true));
        }
        if let Some(content) = d.content {
            spec.insert("content".into(), json!(content));
        }
        if d.code {
            spec.insert("code".into(), json!(true));
        }
        // prosemirror-tables 角色：tableEditing/columnResizing/TableMap 依此工作；
        // 表格成员节点同时需要 isolating（防止事务意外拆散结构）。
        if let Some(role) = table_role(d.pm_name) {
            spec.insert("tableRole".into(), json!(role));
            spec.insert("isolating".into(), json!(true));
        }
        if !d.attrs.is_empty() {
            spec.insert("attrs".into(), attrs_json(d.attrs));
        }
        nodes.insert(d.pm_name.to_string(), Value::Object(spec));
    }

    let mut marks = Map::new();
    for d in MARKS {
        let mut spec = Map::new();
        spec.insert("attrs".into(), attrs_json(d.attrs));
        marks.insert(d.pm_name.to_string(), Value::Object(spec));
    }

    json!({
        "$azodoc": {
            "generated_by": "azodoc-pm (generate bin)",
            "source_of_truth": "engine/crates/azodoc-pm/src/mapping.rs",
            "regenerate": "cargo run -p azodoc-pm --bin generate",
        },
        "nodes": Value::Object(nodes),
        "marks": Value::Object(marks),
    })
}

/// `gen/aludel-schema.json` 的文件内容（含尾换行）。
pub fn aludel_schema_json() -> String {
    let mut s = serde_json::to_string_pretty(&schema_spec()).expect("schema spec 序列化失败");
    s.push('\n');
    s
}

/// `gen/schema.mjs` 的文件内容。
pub fn schema_mjs() -> String {
    let body = serde_json::to_string_pretty(&schema_spec()).expect("schema spec 序列化失败");
    format!(
        "// @generated by azodoc-pm — DO NOT EDIT.\n\
         // 唯一事实源：engine/crates/azodoc-pm/src/mapping.rs（Prima ↔ ProseMirror 映射表）。\n\
         // 重新生成：cargo run -p azodoc-pm --bin generate\n\
         // 用法：import {{ schemaSpec }} from \"./schema.mjs\";\n\
         //       const schema = Schema.fromJSON(schemaSpec)\n\
         export const schemaSpec = {body};\n\
         export default schemaSpec;\n"
    )
}
